### ISSUE TITLE
Detalles

### ISSUE THREAD

**Issue by gisuss** [starchild92/GPSCars#11]
1. En la sección de "Listar Vendedores", el botón verde en la parte superior derecha de la pantalla, dice "Agregar Vehículo" en vez de "Agregar Vendedor".

2. En la sección de "Agregar Plan", la parte del formulario para agregar el tiempo dice "Tiempoen días" en vez de "Tiempo en días" (solo falta un espacio entre "Tiempo"  y  "en") XD.

3. En la sección de "Agregar Vendedor", la parte de agregar clave, pon "Agregue Clave" en vez de "form.password" y "Confirme Clave" en vez de "form.password_confirmation".

4. Esta bien que si yo modifico las tarifas de los planes, a las ventas ya concretadas también se les modifica el precio en el pdf?

                 Estos son los únicos detalles que vi, lo demás esta fino!

**Comment by starchild92** [comment]
Respecto al ítem 4.
Si hoy dice "Plan A, precio 10" y luego generas una venta, en ese momento la venta tiene precio 10, si luego cambias el precio a 20 del plan A, las ventas anteriores y nuevas cambian de precio.

Ese comportamiento se puede modificar guardando en la tabla de venta el precio que había en el plan en el momento que se hizo la venta.

**Comment by gisuss** [comment]
Modifique algunos títulos y algunos botones jeje pero hay botones que no se como cambiar..

Respecto al punto 4, habría que saber bien como lo maneja el cliente para no hacer dos veces esa parte.. Le pregunto en la tarde

**Comment by gisuss** [comment]
Como no supe trabajar en mi rama tomando la tuya, hice los cambios directamente en tu rama pero antes los probé aquí en mi pc.. el Punto 1 ya esta listo :]
