### ISSUE TITLE
Nuevas Modificaciones

### ISSUE THREAD

**Issue by gisuss** [starchild92/GPSCars#15]
1. Agregar un nuevo atributo a vehículo -> "Color".

2. Agregar el correo electrónico del cliente (debajo del nombre del cliente) en el reporte de "Ventas Próximas a Vencer".

3. Al momento de que el admin quiera modificar (o hacer otra operación) a algún vendedor, que no le pida clave.

4. En la sección de ventas, la parte de "nombre de dispositivo" me dijo que pusiera mas bien "numero del gps" como campo de texto.

5. En la sección de ventas, la parte de "Ubicación de las antenas" me dijo que pusiera mas bien "Ubicación del gps".

6. En el Menú, agregar una opción (solo admin) que se llame "Respaldo" para que en el momento que el quiera, le genere un reporte de toda la BD en cuanto a clientes y ventas se refiere en formato xls (si se puede) o en pdf.

7. Le gusto la idea de hacer una barra buscadora (similar a la de google) en el tope de la pagina de inicio y que esta al momento de escribir vaya arrojando sugerencias (se puede?).

8. En la sección de "Lista de vehículos" quiere que aparezcan todo lo que ya esta y ademas el numero imei del dispositivo (esto creo que si es un cambio grande :bowtie:).

[Considero que hay que reestructurar el formulario de Ventas]
9. Lo digo porque empezó diciendo que la mayoría de sus clientes tienen de dos o mas vehículos y que no todos escogen el mismo plan para sus vehículos..

**Comment by gisuss** [comment]
El punto 8 y 9 están relacionados. Algunos datos del formulario de ventas van a completar la tabla de vehículo.

El punto 7 es necesario por si algún cliente llega y quiere que le modifiquen un vehículo, un teléfono u otra cosa.. es para no tener que revisar y buscar entre todos.

Ahh lo olvidaba:

10. En "agregar un cliente", que le quite lo del código internacional.. me pidió disculpas porque primero me había dicho que si y ahora que no..

**Comment by starchild92** [comment]
**1. Listo
2. Listo**
3. En proceso
**4. Listo
5. Listo**
6. **Listo** (_Pero el botón aun no hace nada_)
7. En espera del prototipo de interfaz
8. En proceso
_9. Actualmente se tiene que elegir un plan por cada vehículo, independientemente de la cantidad de vehículos que tiene un cliente._

**Comment by gisuss** [comment]
Estaba pensando algo asi para los puntos 7 y 9. Tu dices que tal :+1: 
![img_20160302_122059](https://cloud.githubusercontent.com/assets/9197987/13467684/828a2724-e071-11e5-98db-6d9080a13340.jpg)

**Comment by starchild92** [comment]
9. En la venta se tiene que agregar un vehículo por venta, no pueden ser varios.

**Comment by gisuss** [comment]
Humm bueno, eso no le pareció por lo lento del proceso :S

**Comment by starchild92** [comment]
Ya se removió el atributo "código país" de la entidad Telefono

**Comment by starchild92** [comment]
Ye agregue los DataTables
