### ISSUE TITLE
Bugs en Agregar Plan y Agregar Tipo de Combustible

### ISSUE THREAD

**Issue by gisuss** [starchild92/GPSCars#16]
Ayer cuando quise agregar un plan me salio ese error de abajo. Me paso cuando puse un precio con decimales y luego lo mismo con un precio sin decimales

![plan](https://cloud.githubusercontent.com/assets/9197987/13464313/c257ca6e-e062-11e5-9a3a-dfa0443d28de.jpg)

**Comment by gisuss** [comment]
El error no es con la BD sino con tipoplan: show.html.twig ya que me acabo de fijar que no esta en la carpeta    GPSCars/src/AppBundle/Resources/views/TipoPlan

![planes2](https://cloud.githubusercontent.com/assets/9197987/13464586/050d1e80-e064-11e5-8a97-acba99eb2a30.jpg)

**Comment by gisuss** [comment]
Lo que pienso es que como la pantalla de tipoplan: show.html.twig no es muy vistosa, haz que el controlador vaya a index.html.twig que esta mejor

**Comment by gisuss** [comment]
Si, igualmente en Tipos de combustible. Haz que una vez que se edite o se cree una nueva instancia, se vaya al index en vez del show :]

~Creo que esta bien, igual tu eres el que decide XD

**Comment by starchild92** [comment]
Si, quite varios show pero olvide que después de agregar el controlador redirige a la vista show.

**Comment by gisuss** [comment]
:+1:
