### ISSUE TITLE
Venta: Funcionalidad

### ISSUE THREAD

**Issue by starchild92** [starchild92/GPSCars#19]
Después de agregar una venta, se deben mostrar las opciones de:
**"Guardar e Imprimir"
"Guardar"**

Generando el reporte del documento que está adjunto en el formato de Dropbox. "**FORMULARIO GPS CARACAS**"

**Comment by starchild92** [comment]
Arriba a la Derecha hay un botón para descargar el reporte de la venta.
Obligatoriamente cuando se agrega se guarda por eso no hay un botón de guardar.

![screenshot 2016-03-13 10 51 44](https://cloud.githubusercontent.com/assets/13983138/13729679/0b024944-e90d-11e5-91d4-1bde53da4d3b.png)

**Comment by starchild92** [comment]
Asi se ven los reportes.
[Reporte Venta #12.pdf](https://github.com/starchild92/GPSCars/files/171062/Reporte.Venta.12.pdf)

**Comment by starchild92** [comment]
Se me había olvidado que el puso un formato u.u, tendré que cambiarlos.

**Comment by starchild92** [comment]
Así se ven los reportes como él los pidio.
[Reporte Venta #12.pdf](https://github.com/starchild92/GPSCars/files/171098/Reporte.Venta.12.pdf)

**Comment by starchild92** [comment]
Generar dos modelos de reporte y el botón cambio de lugar.
![screenshot 2016-03-13 12 43 04](https://cloud.githubusercontent.com/assets/13983138/13730133/28390a50-e919-11e5-9112-af5cfef6881d.png)

**Comment by gisuss** [comment]
Si jaja cuando vi el primer reporte dije lo mismo XD esta mejor el que
diseñaste, pero ya esta acostumbrado a su formato prehistórico jaja

Cuando puedas, pasame una sentencia SQL para agregar un usuario a
phpmyadmin porque hice drop jeje

Te esta quedando cool, de pana!

2016-03-13 12:43 GMT-04:30 Luis <notifications@github.com>:
