### ISSUE TITLE
Full Compatibilidad con Google Chrome

### ISSUE THREAD

**Issue by starchild92** [starchild92/GPSCars#2]
Estoy usando "Version 48.0.2564.82 Built on Ubuntu 14.04, running on elementary OS 0.3.2
" y al visualizar los botones de "select" de las opciones por ejemplo, elegir el tipo de combustible al agrega un vehículo, las opciones de select no se muestran en la lista. @gisuss te toca verificar si en google chrome en windows este problema persiste.
Por otro lado el problema no aparece cuando se usa Firefox en el mismo sistema operativo.

**Comment by starchild92** [comment]
Verifique en mi laptop con Windows 10 y Google Chrome y el problema no está presente. Mañana hare pruebas sobre el navegador en Linux para ver si el problema persiste.

**Comment by gisuss** [comment]
@starchild92 Bueno, en Windows 7 usando Chrome y Firefox no se muestran las opciones de combustible al momento de añadir cliente.

**Comment by gisuss** [comment]
@starchild92 Omite lo anterior, para poder seleccionar combustible, primero hay que añadir uno en la opción "Tipos de Combustible".. Añadí Diesel y Gas a esa tabla.

**Comment by starchild92** [comment]
Si bueno, esa opción de los tipos de combustible es trivial y lo puede hacer cualquiera, en principio no afecta en nada la venta o los dispositivos.
Cuando se vaya hacer la entrega se poblan las tablas como esa con arreglos para funcionalidad minima del sistema, por ahora no se como hacer eso solo, y cada vez que hago drop de la base de datos se borran y los tengo que añadir otra vez hahahaha

**Comment by gisuss** [comment]
Ah bueno, esa es una de las cosas que hay que tomar en cuenta jaja, poblar las tablas y si, no creo que haya rollos con lo de añadir combustible, dejemoslo así jeje

**Comment by gisuss** [comment]
@starchild92 Lo que te proponía por sms era quitar la opción de añadir dispositivos, que todos se agreguen al momento de registrar una venta, o sea, se le asigna un imei, un nombre (el cual es el nombre y apellido del cliente) y que la fecha de agregado sea la fecha del sistema sin modificación (así como hiciste con "añadir Cliente").

Ahora, así como te lo planteo, ¿se puede mostrar seguimiento de los dispositivos por cliente? o sea, ¿al momento de imprimir me van a salir los clientes, sus vehículos y sus dispositivos por vehículo?

**Comment by starchild92** [comment]
Entiendo, en "**Venta**" cambiare el dispositivo para que tenga que ingresar el campo _nombre_ e _imei_, pero solo podrá agregar uno. y la opción de agregar dispositivo desde ** /dispositivo/new** desaparecerá

**Comment by gisuss** [comment]
OK, hasta ahora eso he visto por aquí.

**Comment by gisuss** [comment]
@starchild92 En la parte de "¿No recuerda su contraseña?" el mensaje "ENVÍAME EL ENLACE DE RESTAURACIÓN" no cabe en la plantilla del botón, se puede poner ""ENVÍAME ENLACE DE RESTAURACIÓN" para que quepa

**Comment by starchild92** [comment]
Pasa un captura para ver.

**Comment by gisuss** [comment]
![capture](https://cloud.githubusercontent.com/assets/9197987/12981324/5f9e76ee-d0b2-11e5-838d-922c593e34e3.jpg)

**Comment by gisuss** [comment]
me di cuenta que a pantalla completa no se ve mal, pero a pantalla pequeña si, habría que poner un mensaje corto, de una palabra o dos para que se vea bien en todos los dispositivos

**Comment by starchild92** [comment]
no ya se como solucionar eso. cambiando la propiedad col-*-xs del css

**Comment by gisuss** [comment]
Hay otro pequeño detalle que veo en el login, el tamaño de la casilla gris del muñeco es mas pequeña que la de la llave, la ves?
![capture2](https://cloud.githubusercontent.com/assets/9197987/12982223/0fa71728-d0b6-11e5-9720-052f7ab08d44.jpg)

**Comment by starchild92** [comment]
![Uploading Screen Shot 2016-02-11 at 11.58.23.png…]()
