### ISSUE TITLE
Generar Reportes

### ISSUE THREAD

**Issue by gisuss** [starchild92/GPSCars#28]
Epale Luis, estaba probando el proyecto y cuando voy a generar el reporte (bien sea el A o el B), me sale esta pantalla. Estoy desde tu rama.

![generar-reportes](https://cloud.githubusercontent.com/assets/9197987/13820795/12b5db22-eb71-11e5-9b65-fc979b372968.jpg)

Otra cosa, cuando a un cliente se le vence el plan y decide renovar (el mismo plan u otro), ¿como se hace eso? lo pregunto porque como me perdí toda una semana, siento que hay muchos cambios jeje

**Comment by gisuss** [comment]
> cuando voy a generar el reporte (bien sea el A o el B), me sale esta pantalla. Estoy desde tu rama.

Es cuando intento generar todos los reportes.

**Comment by starchild92** [comment]
Ese error viene porque tienes que entrar en las configuraciones del proyecto y modificar la linea que incluye la aplicación que genera los archivos pdf, Esa linea es distinta cuando corres el proyecto en Linux o en Windows, y como programo en ambos la cambio cada rato, la ultima vez que subí cambios estaba en Linux y quedo así.
