### ISSUE TITLE
Verificación de los Formularios

### ISSUE THREAD

**Issue by starchild92** [starchild92/GPSCars#4]
@gisuss otra tarea que te toca es verficar las validaciones mas evidentes. Por ejemplo, que cuando insertes un usuario, el nombre de usuario no se repita. La del ejemplo ya está validada. Trata de que sean las más lógicas y al final vemos las de teclado, es decir, validar que no coloque numero donde se piden letras. Etc.

Esta es la tarea, en la que creo, nos deberiamos enfocar por lo menos despues de crear formularios nuevos. Las validaciones que encuentres me las dejas por aqui mismo.

**Comment by starchild92** [comment]
Formulario: **Vehiculo**

> No se pueden permitir valores ""#%$&%#$," en la placa.

**Comment by gisuss** [comment]
@starchild92 Ok, estoy verificando la validación de datos de formularios. En la "cédula" esta correcto que solo reciba números, pero:

1. en el "Nombre" y "Apellido": debería recibir solo letras
2. en el "teléfono": debería solo recibir números
3. en la "placa": debería recibir un string de 7 caracteres alfanuméricos (y almacenarlos en mayúsculas)

**Comment by starchild92** [comment]
Puedes bajar de mi rama la corrección de este bug.

**Comment by starchild92** [comment]
@gisuss cuando vayas a verificar es necesario que hagas `php app/console doctrine:schema:update --force` para actualizar la base de datos.

**Comment by gisuss** [comment]
Ok @starchild92 ya verifiqué en tu rama y encontré estos bugs:

- En "Apellido" sigue aceptando números.
- En "Código de área" debería recibir solo 4 dígitos numéricos.
- En "email": puse "@algoloco.com" y me lo acepto.

Lo que creo que puede funcionar para el email es hacer una tabla (la cual debemos poblar con @gmail.com , @yahoo.com , @hotmail.com y esos) y que sean desplegables como en el caso de "Tipo de Combustible".

En el "Código de área" podemos hacer lo mismo y poblando con todos los códigos de área existentes o simplemente validar que acepte solo 4 números. Creo que la segunda opción es mejor.

**Comment by starchild92** [comment]
Lo de la tabla de los **mail** no es muy factible, porque yo tengo por ejemplo, outlook.com, yahoo.es, uc.edu.ve; entonces a la hora de escribir el mail es fastidioso buscar cual es, en cambio, mientras tenga la nomenclatura de un mail 'arroba''punto''domino''punto''lodemas' está bien.

Respecto al **código de área**, hay países donde el código de área tiene mas números, no sé si el solo recibe números nacionales. XD Porque si en principio todos son de Venezuela (+58) entonces no es necesario el código internacional.

Verificaré y corregiré inmediatamente el **apellido**.

**Comment by gisuss** [comment]
Le voy a preguntar si solo recibe clientes con números nacionales.. la otra vez que hablamos me dio a entender que tiene clientes con números internacionales, pero mejor le pregunto para que me lo asegure.

**Comment by gisuss** [comment]
@starchild92 Le acabo de preguntar y me dijo que tiene clientes de ambos formatos; nacionales e internacionales.. Entonces déjalo como esta y que los que manejen el sistema tengan cuidado con ese campo
