### ISSUE TITLE
Formulario Ventas

### ISSUE THREAD

**Issue by gisuss** [starchild92/GPSCars#7]
Hola @lapv20 

1. Creé un nuevo cliente "Katherine Vill4l0b0s" y le puse dos vehículos (un McLaren 2014 y un Chevetti 1942), al momento de crear una venta debería dejarme asignarle como máximo 2 dispositivos (porque Katherine tiene dos vehículos registrados), el problema que vi es que no me permite asignarle el segundo dispositivo desde la misma venta.

2. Lo otro es en cuanto a los "tipos de planes", ¿no habrá un script que pueble algunas tablas al momento de crear la BD para fines de sencillez?

3. Otra cosa que vi es que todas las fechas (excepto la fecha de próximo cobro) deberían ser las del sistema.

**Comment by starchild92** [comment]
1. Yo estoy asumiendo que para cada venta se tiene un solo dispositivo porque los dispositivos no están asociados a ningún vehículo entonces no hay forma de comunicar la información del la venta con el vehículo. Por otro lado está el manejo de los planes, si tuviese muchos dispositivos en una sola venta entonces, tendría en esa misma venta muchos planes aunque fuese el mismo plan para todos los dispositivos. Tampoco los dispositivos están asociados a número de teléfono.

**Comment by starchild92** [comment]
2. Lo de poblar la base de datos, lo puedes investigar o lo podemos dejar así, al final esos valores los debe colocar el dueño del negocio que es quien decide como administrar el sistema.

**Comment by starchild92** [comment]
-3. Lo de las fechas sigue requiriendo revisión, pretendo manejar todas la fechas de los registros y ventas automáticamente. A medida que vayamos avanzando en esto, entonces deberíamos ir revisando.
