### ISSUE TITLE
Edicion de Usuarios

### ISSUE THREAD

**Issue by gisuss** [starchild92/GPSCars#8]
Me acabo de dar cuenta que en el menú de edición de usuarios (desde el usuario administrador) no sale el botón verde de "Editar Usuario" 

Otra cosa, hagamos que todos los botones de Actualización, edición y creación sean verdes (como los de agregar teléfono o vehículo en el formulario de "Agregar Cliente")

**Comment by gisuss** [comment]
Ahh ya lo vi, pasa que esta en ingles (submit me) y no esta abajo XD..

Estaba modificando roles de usuario y actividad/inactividad de sus cuentas y lo hace bien, lo que te iba a preguntar es que me pidió clave, ¿se puede hacer que el admin haga ese tipo de cosas sin requerir de clave? por ejemplo para bloquear una cuenta y ceder un rol de usuario.

**Comment by starchild92** [comment]
Si, claro es cuestión de crear un formulario que no requiera los campos de la clave. Cuando lo implemente cerraré el tema. :)

**Comment by gisuss** [comment]
Antes de que lo cierres, recuerda poner el botón en verde abajo, y los textos en español jaja
